### ISSUE TITLE
Multiple PHP versions in CI

### ISSUE THREAD

**Issue by szepeviktor** [j-arens/container#5]
PHP 7.1 is EOL https://www.php.net/supported-versions.php

Could we run on 7.2, 7.3 and 7.4?
https://github.com/shivammathur/setup-php#matrix-testing

and keep composer cache
https://github.com/shivammathur/setup-php#cache-dependencies

**Comment by j-arens** [comment]
Good idea, I'll get this setup. Probably gonna keep 7.1 though because I plan on using this in WordPress projects that likely won't be on the latest php yet.

**Comment by szepeviktor** [comment]
:) Actually I'm currently trying to build it into WordPress.
Could you show me your implementation?

**Comment by j-arens** [comment]
I'm not really doing anything special to integrate with WordPress, just wanted to have my own lightweight container :man_shrugging:. This implementation is based loosely around Laravel's service container though, so it follows some of the same rules. I think the best public example I have would be [in this older project](https://github.com/j-arens/elmtr-melody/blob/master/plugin/bootstrap.php). It's actually using [this container](https://github.com/downshiftorg/container) but they are very similar.
